package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"html"
	"html/template"
	"io"
	"io/fs"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

const generatedMarker = "<!-- generated by Onyx; do not edit -->"
const publicMarker = ".onyx-generated"

type Config struct {
	Root       string
	ConfigPath string
	SiteTitle  string
	Source     string
	BaseURL    string
	Theme      string
	Search     bool
	Backlinks  bool
	ShowSource bool
}

type Vault struct {
	Config       Config
	Notes        []*Page
	Home         *Page
	ByPath       map[string]*Page
	ByBase       map[string][]*Page
	AssetsByPath map[string]string
	AssetsByBase map[string][]string
}

type Page struct {
	SourceRel   string
	SourceAbs   string
	PageRel     string
	URL         string
	SourceURL   string
	Title       string
	Body        string
	HTML        template.HTML
	Text        string
	Excerpt     string
	Headings    []string
	Tags        []string
	Outgoing    map[string]bool
	Backlinks   []LinkView
	FrontMatter map[string]string
	IsHome      bool
	Generated   bool
}

type LinkView struct {
	Title string `json:"title"`
	URL   string `json:"url"`
	Path  string `json:"path"`
}

type SearchItem struct {
	Title    string   `json:"title"`
	URL      string   `json:"url"`
	Path     string   `json:"path"`
	Excerpt  string   `json:"excerpt"`
	Headings []string `json:"headings,omitempty"`
	Tags     []string `json:"tags,omitempty"`
}

type TemplateData struct {
	Site       SiteView
	Page       *Page
	Nav        template.HTML
	Backlinks  []LinkView
	Search     bool
	ShowSource bool
	Generated  template.HTML
	RootScript template.JS
	HomeURL    string
	CSSURL     string
	JSURL      string
}

type SiteView struct {
	Title   string
	BaseURL string
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout, stderr io.Writer) int {
	if err := runErr(args, stdout, stderr); err != nil {
		fmt.Fprintf(stderr, "onyx: %v\n", err)
		return 1
	}
	return 0
}

func runErr(args []string, stdout, stderr io.Writer) error {
	if len(args) > 1 {
		return errors.New("usage: onyx [site-root-or-child]")
	}

	start := "."
	if len(args) == 1 {
		start = args[0]
	}

	root, configPath, err := findConfig(start)
	if err != nil {
		return err
	}

	cfg, err := readConfig(root, configPath)
	if err != nil {
		return err
	}

	warnings, err := buildSite(cfg)
	if err != nil {
		return err
	}
	for _, warning := range warnings {
		fmt.Fprintf(stderr, "warning: %s\n", warning)
	}
	fmt.Fprintf(stdout, "Onyx built %d pages into %s\n", countPages(cfg.Root), filepath.Join(cfg.Root, "public"))
	return nil
}

func countPages(root string) int {
	count := 0
	_ = filepath.WalkDir(filepath.Join(root, "public"), func(p string, d fs.DirEntry, err error) error {
		if err == nil && !d.IsDir() && d.Name() == "index.html" {
			count++
		}
		return nil
	})
	if _, err := os.Stat(filepath.Join(root, "index.html")); err == nil {
		count++
	}
	return count
}

func findConfig(start string) (string, string, error) {
	abs, err := filepath.Abs(start)
	if err != nil {
		return "", "", err
	}
	info, err := os.Stat(abs)
	if err != nil {
		return "", "", err
	}
	if !info.IsDir() {
		abs = filepath.Dir(abs)
	}

	for {
		candidate := filepath.Join(abs, "onyx.ini")
		if _, err := os.Stat(candidate); err == nil {
			return abs, candidate, nil
		}
		parent := filepath.Dir(abs)
		if parent == abs {
			return "", "", errors.New("no onyx.ini found in this directory or its parents")
		}
		abs = parent
	}
}

func readConfig(root, configPath string) (Config, error) {
	values, err := parseINI(configPath)
	if err != nil {
		return Config{}, err
	}

	cfg := Config{
		Root:       root,
		ConfigPath: configPath,
		SiteTitle:  valueOr(values, "site_title", "Onyx"),
		Source:     valueOr(values, "source", "docs"),
		BaseURL:    cleanBaseURL(valueOr(values, "base_url", "/")),
		Theme:      valueOr(values, "theme", "theme"),
		Search:     boolOr(values, true, "search", "build.search"),
		Backlinks:  boolOr(values, true, "backlinks", "build.backlinks"),
		ShowSource: boolOr(values, true, "show_source", "publish_raw_markdown"),
	}

	if filepath.IsAbs(cfg.Source) {
		return Config{}, errors.New("source must be relative to the site root")
	}
	if filepath.IsAbs(cfg.Theme) {
		return Config{}, errors.New("theme must be relative to the site root")
	}

	sourceDir := filepath.Join(root, filepath.FromSlash(cfg.Source))
	info, err := os.Stat(sourceDir)
	if err != nil {
		return Config{}, fmt.Errorf("source directory %q: %w", cfg.Source, err)
	}
	if !info.IsDir() {
		return Config{}, fmt.Errorf("source %q is not a directory", cfg.Source)
	}

	return cfg, nil
}

func parseINI(filename string) (map[string]string, error) {
	data, err := os.ReadFile(filename)
	if err != nil {
		return nil, err
	}
	text := strings.ReplaceAll(string(bytes.TrimPrefix(data, []byte("\xef\xbb\xbf"))), "\r\n", "\n")
	values := map[string]string{}
	section := ""

	for lineNo, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = strings.ToLower(strings.TrimSpace(line[1 : len(line)-1]))
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("%s:%d: expected key = value", filename, lineNo+1)
		}
		key = strings.ToLower(strings.TrimSpace(key))
		val = stripQuotes(strings.TrimSpace(stripInlineComment(val)))
		if section != "" {
			values[section+"."+key] = val
		}
		values[key] = val
	}

	return values, nil
}

func stripInlineComment(s string) string {
	inQuote := rune(0)
	for i, r := range s {
		if r == '\'' || r == '"' {
			if inQuote == 0 {
				inQuote = r
			} else if inQuote == r {
				inQuote = 0
			}
			continue
		}
		if inQuote == 0 && (r == '#' || r == ';') {
			if i == 0 || unicode.IsSpace(rune(s[i-1])) {
				return strings.TrimSpace(s[:i])
			}
		}
	}
	return s
}

func stripQuotes(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func valueOr(values map[string]string, key, fallback string) string {
	if v, ok := values[key]; ok && strings.TrimSpace(v) != "" {
		return strings.TrimSpace(v)
	}
	return fallback
}

func boolOr(values map[string]string, fallback bool, keys ...string) bool {
	for _, key := range keys {
		if raw, ok := values[key]; ok {
			switch strings.ToLower(strings.TrimSpace(raw)) {
			case "1", "true", "yes", "on":
				return true
			case "0", "false", "no", "off":
				return false
			}
		}
	}
	return fallback
}

func cleanBaseURL(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		s = "/"
	}
	if !strings.HasSuffix(s, "/") {
		s += "/"
	}
	return s
}

func buildSite(cfg Config) ([]string, error) {
	if err := ensureRootIndexWritable(filepath.Join(cfg.Root, "index.html")); err != nil {
		return nil, err
	}
	if err := ensureNoJekyll(cfg.Root); err != nil {
		return nil, err
	}

	vault, warnings, err := loadVault(cfg)
	if err != nil {
		return warnings, err
	}
	renderVault(vault, &warnings)
	computeBacklinks(vault)

	if err := preparePublic(filepath.Join(cfg.Root, "public")); err != nil {
		return warnings, err
	}
	if err := writeAssets(vault); err != nil {
		return warnings, err
	}
	if err := writePages(vault); err != nil {
		return warnings, err
	}
	if cfg.Search {
		if err := writeSearchIndex(vault); err != nil {
			return warnings, err
		}
	}

	return warnings, nil
}

func ensureRootIndexWritable(filename string) error {
	data, err := os.ReadFile(filename)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if bytes.Contains(data, []byte(generatedMarker)) ||
		bytes.Contains(data, []byte(html.EscapeString(generatedMarker))) ||
		isBlankFile(data) {
		return nil
	}
	return fmt.Errorf("%s exists and is not marked as Onyx-generated", filename)
}

func ensureNoJekyll(root string) error {
	filename := filepath.Join(root, ".nojekyll")
	if _, err := os.Stat(filename); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(filename, []byte("Generated by Onyx so GitHub Pages serves static files without Jekyll.\n"), 0o644)
}

func isBlankFile(data []byte) bool {
	if len(bytes.TrimSpace(data)) == 0 {
		return true
	}
	if bytes.HasPrefix(data, []byte{0xff, 0xfe}) {
		for _, b := range data[2:] {
			if b != 0 && b != '\r' && b != '\n' && b != '\t' && b != ' ' {
				return false
			}
		}
		return true
	}
	return false
}

func preparePublic(publicDir string) error {
	info, err := os.Stat(publicDir)
	if err == nil {
		if !info.IsDir() {
			return fmt.Errorf("%s exists and is not a directory", publicDir)
		}
		if _, err := os.Stat(filepath.Join(publicDir, publicMarker)); err != nil {
			return fmt.Errorf("%s exists but is missing %s; refusing to overwrite", publicDir, publicMarker)
		}
		if err := os.RemoveAll(publicDir); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	if err := os.MkdirAll(publicDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(publicDir, publicMarker), []byte("generated by Onyx\n"), 0o644)
}

func loadVault(cfg Config) (*Vault, []string, error) {
	sourceDir := filepath.Join(cfg.Root, filepath.FromSlash(cfg.Source))
	vault := &Vault{
		Config:       cfg,
		ByPath:       map[string]*Page{},
		ByBase:       map[string][]*Page{},
		AssetsByPath: map[string]string{},
		AssetsByBase: map[string][]string{},
	}
	var warnings []string

	err := filepath.WalkDir(sourceDir, func(abs string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if abs == sourceDir {
			return nil
		}
		if shouldSkipName(d.Name()) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}

		relOS, err := filepath.Rel(sourceDir, abs)
		if err != nil {
			return err
		}
		rel := filepath.ToSlash(relOS)
		if hasSkippedComponent(rel) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}

		if strings.EqualFold(filepath.Ext(d.Name()), ".md") {
			page, excluded, err := readPage(abs, rel)
			if err != nil {
				return err
			}
			if excluded {
				warnings = append(warnings, rel+": excluded by frontmatter")
				return nil
			}
			vault.Notes = append(vault.Notes, page)
			return nil
		}

		vault.addAsset(rel)
		return nil
	})
	if err != nil {
		return nil, warnings, err
	}

	sort.Slice(vault.Notes, func(i, j int) bool {
		return strings.ToLower(vault.Notes[i].SourceRel) < strings.ToLower(vault.Notes[j].SourceRel)
	})

	for _, note := range vault.Notes {
		note.PageRel = strings.TrimSuffix(note.SourceRel, path.Ext(note.SourceRel))
		vault.ByPath[strings.ToLower(note.PageRel)] = note
		base := strings.ToLower(path.Base(note.PageRel))
		vault.ByBase[base] = append(vault.ByBase[base], note)
	}

	for _, list := range vault.ByBase {
		sort.Slice(list, func(i, j int) bool {
			return strings.ToLower(list[i].SourceRel) < strings.ToLower(list[j].SourceRel)
		})
	}

	vault.Home = chooseHome(vault)
	if vault.Home == nil {
		vault.Home = generatedHome(vault)
		vault.Notes = append([]*Page{vault.Home}, vault.Notes...)
	}
	vault.Home.IsHome = true

	for _, note := range vault.Notes {
		if note.IsHome {
			note.URL = ""
		} else {
			note.URL = "public/" + escapeURLPath(note.PageRel) + "/"
		}
		if note.SourceRel != "" {
			note.SourceURL = escapeURLPath(path.Join(cfg.Source, note.SourceRel))
		}
	}
	if vault.Home.Generated {
		updateGeneratedHome(vault)
	}

	return vault, warnings, nil
}

func shouldSkipName(name string) bool {
	if strings.HasPrefix(name, ".") {
		return true
	}
	switch strings.ToLower(name) {
	case ".obsidian", ".git", ".trash":
		return true
	}
	return false
}

func hasSkippedComponent(rel string) bool {
	for _, part := range strings.Split(rel, "/") {
		if shouldSkipName(part) {
			return true
		}
	}
	return false
}

func readPage(abs, rel string) (*Page, bool, error) {
	data, err := os.ReadFile(abs)
	if err != nil {
		return nil, false, err
	}
	text := normalizeNewlines(stripUTF8BOM(string(data)))
	frontMatter, body := splitFrontMatter(text)

	if strings.EqualFold(frontMatter["publish"], "false") || truthy(frontMatter["draft"]) {
		return nil, true, nil
	}

	title := strings.TrimSpace(frontMatter["title"])
	if title == "" {
		title = firstHeading(body)
	}
	if title == "" {
		title = strings.TrimSuffix(path.Base(rel), path.Ext(rel))
	}

	return &Page{
		SourceRel:   rel,
		SourceAbs:   abs,
		Title:       title,
		Body:        body,
		FrontMatter: frontMatter,
		Outgoing:    map[string]bool{},
	}, false, nil
}

func stripUTF8BOM(s string) string {
	return strings.TrimPrefix(s, "\ufeff")
}

func normalizeNewlines(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	return strings.ReplaceAll(s, "\r", "\n")
}

func splitFrontMatter(text string) (map[string]string, string) {
	frontMatter := map[string]string{}
	if !strings.HasPrefix(text, "---\n") {
		return frontMatter, text
	}

	lines := strings.Split(text, "\n")
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "---" {
			for _, line := range lines[1:i] {
				key, value, ok := strings.Cut(line, ":")
				if !ok {
					continue
				}
				frontMatter[strings.ToLower(strings.TrimSpace(key))] = stripQuotes(strings.TrimSpace(value))
			}
			return frontMatter, strings.Join(lines[i+1:], "\n")
		}
	}
	return map[string]string{}, text
}

func truthy(s string) bool {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

func firstHeading(body string) string {
	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		if level, text, ok := heading(trimmed); ok && level == 1 {
			return stripInlineMarkdown(text)
		}
	}
	return ""
}

func chooseHome(vault *Vault) *Page {
	if page := vault.ByPath["index"]; page != nil {
		return page
	}
	if page := vault.ByPath["home"]; page != nil {
		return page
	}
	return nil
}

func generatedHome(vault *Vault) *Page {
	return &Page{
		Title:     vault.Config.SiteTitle,
		Text:      vault.Config.SiteTitle,
		Excerpt:   "Generated index",
		Outgoing:  map[string]bool{},
		IsHome:    true,
		Generated: true,
	}
}

func updateGeneratedHome(vault *Vault) {
	var b strings.Builder
	b.WriteString("<p>This site was generated from a folder of Markdown notes.</p>\n")
	b.WriteString("<ul>\n")
	for _, note := range vault.Notes {
		if note.Generated {
			continue
		}
		b.WriteString(`<li><a href="`)
		b.WriteString(html.EscapeString(relativeURL(vault.Home, note.URL)))
		b.WriteString(`">`)
		b.WriteString(html.EscapeString(note.Title))
		b.WriteString("</a></li>\n")
	}
	b.WriteString("</ul>\n")
	vault.Home.HTML = template.HTML(b.String())
}

func (v *Vault) addAsset(rel string) {
	key := strings.ToLower(strings.TrimPrefix(path.Clean(rel), "./"))
	v.AssetsByPath[key] = rel
	base := strings.ToLower(path.Base(rel))
	v.AssetsByBase[base] = append(v.AssetsByBase[base], rel)
}

func renderVault(vault *Vault, warnings *[]string) {
	for _, note := range vault.Notes {
		if note.Generated {
			continue
		}
		renderer := &MarkdownRenderer{
			vault:      vault,
			current:    note,
			warnings:   warnings,
			headingIDs: map[string]int{},
			outgoing:   map[string]bool{},
		}
		result := renderer.Render(note.Body)
		note.HTML = template.HTML(result.HTML)
		note.Text = result.Text
		note.Excerpt = excerpt(result.Text, 220)
		note.Headings = result.Headings
		note.Tags = result.Tags
		note.Outgoing = renderer.outgoing
	}
}

func computeBacklinks(vault *Vault) {
	byRel := map[string]*Page{}
	for _, note := range vault.Notes {
		if !note.Generated {
			byRel[note.PageRel] = note
		}
	}
	for _, note := range vault.Notes {
		for target := range note.Outgoing {
			if page := byRel[target]; page != nil && page != note {
				page.Backlinks = append(page.Backlinks, LinkView{
					Title: note.Title,
					URL:   note.URL,
					Path:  note.SourceRel,
				})
			}
		}
	}
	for _, note := range vault.Notes {
		sort.Slice(note.Backlinks, func(i, j int) bool {
			return strings.ToLower(note.Backlinks[i].Title) < strings.ToLower(note.Backlinks[j].Title)
		})
	}
}

func writeAssets(vault *Vault) error {
	publicDir := filepath.Join(vault.Config.Root, "public")
	themeDir := filepath.Join(vault.Config.Root, filepath.FromSlash(vault.Config.Theme))

	if err := writeThemeOrDefault(filepath.Join(themeDir, "style.css"), filepath.Join(publicDir, "onyx.css"), defaultCSS); err != nil {
		return err
	}
	if err := writeThemeOrDefault(filepath.Join(themeDir, "onyx.js"), filepath.Join(publicDir, "onyx.js"), defaultJS); err != nil {
		return err
	}

	staticDir := filepath.Join(themeDir, "static")
	if info, err := os.Stat(staticDir); err == nil && info.IsDir() {
		return copyDir(staticDir, filepath.Join(publicDir, "theme"))
	}
	return nil
}

func writeThemeOrDefault(source, dest, fallback string) error {
	if data, err := os.ReadFile(source); err == nil {
		return os.WriteFile(dest, data, 0o644)
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(dest, []byte(fallback), 0o644)
}

func copyDir(source, dest string) error {
	return filepath.WalkDir(source, func(abs string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if abs == source {
			return nil
		}
		if shouldSkipName(d.Name()) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(source, abs)
		if err != nil {
			return err
		}
		out := filepath.Join(dest, rel)
		if d.IsDir() {
			return os.MkdirAll(out, 0o755)
		}
		data, err := os.ReadFile(abs)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
			return err
		}
		return os.WriteFile(out, data, 0o644)
	})
}

func writePages(vault *Vault) error {
	pageTemplate, err := loadTemplateSource(vault, "page.html", defaultPageTemplate)
	if err != nil {
		return err
	}
	homeTemplate, err := loadTemplateSource(vault, "home.html", defaultPageTemplate)
	if err != nil {
		return err
	}

	for _, page := range vault.Notes {
		tpl := pageTemplate
		if page.IsHome {
			tpl = homeTemplate
		}
		if err := writePage(vault, page, tpl); err != nil {
			return err
		}
	}
	return nil
}

type templateSource struct {
	name   string
	source string
}

func loadTemplateSource(vault *Vault, name, fallback string) (templateSource, error) {
	themePath := filepath.Join(vault.Config.Root, filepath.FromSlash(vault.Config.Theme), name)
	source := fallback
	if data, err := os.ReadFile(themePath); err == nil {
		source = string(data)
	} else if !os.IsNotExist(err) {
		return templateSource{}, err
	}
	return templateSource{name: name, source: source}, nil
}

func parseTemplateForPage(vault *Vault, page *Page, source templateSource) (*template.Template, error) {
	funcs := template.FuncMap{
		"asset": func(name string) string {
			return relativeURL(page, "public/"+escapeURLPath(name))
		},
	}
	return template.New(source.name).Funcs(funcs).Parse(source.source)
}

func writePage(vault *Vault, page *Page, source templateSource) error {
	tpl, err := parseTemplateForPage(vault, page, source)
	if err != nil {
		return err
	}
	pageView := *page
	pageView.URL = relativeURL(page, page.URL)
	if page.SourceURL != "" {
		pageView.SourceURL = relativeURL(page, page.SourceURL)
	}
	data := TemplateData{
		Site: SiteView{
			Title:   vault.Config.SiteTitle,
			BaseURL: vault.Config.BaseURL,
		},
		Page:       &pageView,
		Nav:        template.HTML(renderNav(vault, page)),
		Backlinks:  relativeLinkViews(page, page.Backlinks),
		Search:     vault.Config.Search,
		ShowSource: vault.Config.ShowSource && page.SourceURL != "",
		Generated:  template.HTML(generatedMarker),
		RootScript: template.JS(strconv.Quote(relativeRoot(page))),
		HomeURL:    relativeURL(page, ""),
		CSSURL:     relativeURL(page, "public/onyx.css"),
		JSURL:      relativeURL(page, "public/onyx.js"),
	}

	var out bytes.Buffer
	if err := tpl.Execute(&out, data); err != nil {
		return err
	}

	if page.IsHome {
		return os.WriteFile(filepath.Join(vault.Config.Root, "index.html"), out.Bytes(), 0o644)
	}

	dest := filepath.Join(vault.Config.Root, "public", filepath.FromSlash(page.PageRel), "index.html")
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dest, out.Bytes(), 0o644)
}

func relativeLinkViews(from *Page, links []LinkView) []LinkView {
	out := make([]LinkView, 0, len(links))
	for _, link := range links {
		link.URL = relativeURL(from, link.URL)
		out = append(out, link)
	}
	return out
}

func writeSearchIndex(vault *Vault) error {
	items := make([]SearchItem, 0, len(vault.Notes))
	for _, page := range vault.Notes {
		items = append(items, SearchItem{
			Title:    page.Title,
			URL:      page.URL,
			Path:     page.SourceRel,
			Excerpt:  page.Excerpt,
			Headings: page.Headings,
			Tags:     page.Tags,
		})
	}
	data, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(filepath.Join(vault.Config.Root, "public", "search-index.json"), data, 0o644)
}

type NavNode struct {
	Name     string
	Path     string
	Page     *Page
	Children map[string]*NavNode
}

func renderNav(vault *Vault, current *Page) string {
	root := &NavNode{Children: map[string]*NavNode{}}
	for _, page := range vault.Notes {
		if page.IsHome {
			continue
		}
		insertNav(root, page)
	}

	var b strings.Builder
	b.WriteString(`<ul class="nav-tree">`)
	b.WriteString(`<li><a`)
	if current.IsHome {
		b.WriteString(` aria-current="page"`)
	}
	b.WriteString(` href="`)
	b.WriteString(html.EscapeString(relativeURL(current, "")))
	b.WriteString(`">Home</a></li>`)
	writeNavChildren(&b, root, current)
	b.WriteString(`</ul>`)
	return b.String()
}

func insertNav(root *NavNode, page *Page) {
	segments := strings.Split(page.PageRel, "/")
	node := root
	prefix := ""
	for _, segment := range segments {
		key := strings.ToLower(segment)
		if prefix == "" {
			prefix = key
		} else {
			prefix += "/" + key
		}
		if node.Children == nil {
			node.Children = map[string]*NavNode{}
		}
		child := node.Children[key]
		if child == nil {
			child = &NavNode{Name: segment, Path: prefix, Children: map[string]*NavNode{}}
			node.Children[key] = child
		}
		node = child
	}
	node.Page = page
	node.Name = page.Title
}

func writeNavChildren(b *strings.Builder, node *NavNode, current *Page) {
	children := make([]*NavNode, 0, len(node.Children))
	for _, child := range node.Children {
		children = append(children, child)
	}
	sort.Slice(children, func(i, j int) bool {
		iFolder := len(children[i].Children) > 0
		jFolder := len(children[j].Children) > 0
		if iFolder != jFolder {
			return iFolder
		}
		return strings.ToLower(children[i].Name) < strings.ToLower(children[j].Name)
	})

	currentPath := strings.ToLower(current.PageRel)
	for _, child := range children {
		b.WriteString("<li>")
		if len(child.Children) > 0 {
			onPath := currentPath == child.Path || strings.HasPrefix(currentPath, child.Path+"/")
			b.WriteString("<details")
			if onPath {
				b.WriteString(" open")
			}
			b.WriteString("><summary>")
			writeNavLabel(b, child, current)
			b.WriteString("</summary><ul>")
			writeNavChildren(b, child, current)
			b.WriteString("</ul></details>")
		} else {
			writeNavLabel(b, child, current)
		}
		b.WriteString("</li>")
	}
}

func writeNavLabel(b *strings.Builder, node *NavNode, current *Page) {
	if node.Page == nil {
		b.WriteString(`<span>`)
		b.WriteString(html.EscapeString(node.Name))
		b.WriteString(`</span>`)
		return
	}
	b.WriteString(`<a`)
	if node.Page == current {
		b.WriteString(` aria-current="page"`)
	}
	b.WriteString(` href="`)
	b.WriteString(html.EscapeString(relativeURL(current, node.Page.URL)))
	b.WriteString(`">`)
	b.WriteString(html.EscapeString(node.Name))
	b.WriteString(`</a>`)
}

type MarkdownRenderer struct {
	vault      *Vault
	current    *Page
	warnings   *[]string
	headingIDs map[string]int
	outgoing   map[string]bool
	headings   []string
}

type RenderResult struct {
	HTML     string
	Text     string
	Headings []string
	Tags     []string
}

func (r *MarkdownRenderer) Render(markdown string) RenderResult {
	markdown = normalizeNewlines(markdown)
	htmlOut := r.renderBlocks(strings.Split(markdown, "\n"))
	text := plainText(markdown)
	return RenderResult{
		HTML:     htmlOut,
		Text:     text,
		Headings: r.headings,
		Tags:     extractTags(markdown),
	}
}

func (r *MarkdownRenderer) renderBlocks(lines []string) string {
	var b strings.Builder
	for i := 0; i < len(lines); {
		line := lines[i]
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			i++
			continue
		}

		if fence, info, ok := fenceStart(trimmed); ok {
			j := i + 1
			var code []string
			for ; j < len(lines); j++ {
				if strings.HasPrefix(strings.TrimSpace(lines[j]), fence) {
					break
				}
				code = append(code, lines[j])
			}
			class := ""
			if info != "" {
				class = ` class="language-` + html.EscapeString(sanitizeClass(info)) + `"`
			}
			b.WriteString("<pre><code")
			b.WriteString(class)
			b.WriteString(">")
			b.WriteString(html.EscapeString(strings.Join(code, "\n")))
			b.WriteString("</code></pre>\n")
			if j < len(lines) {
				i = j + 1
			} else {
				i = j
			}
			continue
		}

		if isTableStart(lines, i) {
			j := i + 2
			for j < len(lines) && strings.Contains(lines[j], "|") && strings.TrimSpace(lines[j]) != "" {
				j++
			}
			b.WriteString(r.renderTable(lines[i:j]))
			i = j
			continue
		}

		if level, text, ok := heading(trimmed); ok {
			title := stripInlineMarkdown(text)
			id := r.uniqueHeadingID(slugify(title))
			r.headings = append(r.headings, title)
			fmt.Fprintf(&b, `<h%d id="%s">%s</h%d>`+"\n", level, html.EscapeString(id), r.renderInline(text), level)
			i++
			continue
		}

		if isHorizontalRule(trimmed) {
			b.WriteString("<hr>\n")
			i++
			continue
		}

		if strings.HasPrefix(strings.TrimLeft(line, " "), ">") {
			j := i
			var quote []string
			for j < len(lines) {
				if strings.TrimSpace(lines[j]) == "" {
					quote = append(quote, "")
					j++
					continue
				}
				if !strings.HasPrefix(strings.TrimLeft(lines[j], " "), ">") {
					break
				}
				quote = append(quote, stripBlockquoteMarker(lines[j]))
				j++
			}
			b.WriteString(r.renderBlockquote(quote))
			i = j
			continue
		}

		if ordered, _, ok := listMarker(line); ok {
			tag := "ul"
			if ordered {
				tag = "ol"
			}
			b.WriteString("<" + tag + ">\n")
			j := i
			for j < len(lines) {
				nextOrdered, nextContent, ok := listMarker(lines[j])
				if !ok || nextOrdered != ordered {
					break
				}
				b.WriteString("<li>")
				b.WriteString(r.renderListItem(nextContent))
				b.WriteString("</li>\n")
				j++
			}
			b.WriteString("</" + tag + ">\n")
			i = j
			continue
		}

		j := i
		var para []string
		for j < len(lines) {
			if strings.TrimSpace(lines[j]) == "" || startsBlock(lines, j) {
				break
			}
			para = append(para, strings.TrimSpace(lines[j]))
			j++
		}
		b.WriteString("<p>")
		b.WriteString(r.renderInline(strings.Join(para, " ")))
		b.WriteString("</p>\n")
		i = j
	}
	return b.String()
}

func fenceStart(line string) (string, string, bool) {
	if strings.HasPrefix(line, "```") {
		return "```", strings.TrimSpace(line[3:]), true
	}
	if strings.HasPrefix(line, "~~~") {
		return "~~~", strings.TrimSpace(line[3:]), true
	}
	return "", "", false
}

func sanitizeClass(s string) string {
	fields := strings.Fields(s)
	if len(fields) == 0 {
		return ""
	}
	s = fields[0]
	var b strings.Builder
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '-' || r == '_' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func startsBlock(lines []string, i int) bool {
	trimmed := strings.TrimSpace(lines[i])
	if trimmed == "" {
		return true
	}
	if _, _, ok := fenceStart(trimmed); ok {
		return true
	}
	if _, _, ok := heading(trimmed); ok {
		return true
	}
	if isHorizontalRule(trimmed) {
		return true
	}
	if strings.HasPrefix(strings.TrimLeft(lines[i], " "), ">") {
		return true
	}
	if _, _, ok := listMarker(lines[i]); ok {
		return true
	}
	return isTableStart(lines, i)
}

func heading(line string) (int, string, bool) {
	count := 0
	for count < len(line) && line[count] == '#' {
		count++
	}
	if count == 0 || count > 6 || count >= len(line) || line[count] != ' ' {
		return 0, "", false
	}
	return count, strings.TrimSpace(line[count+1:]), true
}

func isHorizontalRule(line string) bool {
	if len(line) < 3 {
		return false
	}
	for _, marker := range []rune{'-', '*', '_'} {
		count := 0
		ok := true
		for _, r := range line {
			if unicode.IsSpace(r) {
				continue
			}
			if r != marker {
				ok = false
				break
			}
			count++
		}
		if ok && count >= 3 {
			return true
		}
	}
	return false
}

func stripBlockquoteMarker(line string) string {
	line = strings.TrimLeft(line, " ")
	if strings.HasPrefix(line, ">") {
		line = line[1:]
	}
	return strings.TrimPrefix(line, " ")
}

func (r *MarkdownRenderer) renderBlockquote(lines []string) string {
	first := ""
	for _, line := range lines {
		if strings.TrimSpace(line) != "" {
			first = strings.TrimSpace(line)
			break
		}
	}

	if strings.HasPrefix(first, "[!") {
		end := strings.Index(first, "]")
		if end > 2 {
			kind := strings.ToLower(strings.TrimSpace(first[2:end]))
			title := strings.TrimSpace(first[end+1:])
			if title == "" {
				title = titleCase(kind)
			}
			body := dropFirstNonBlank(lines)
			var b strings.Builder
			b.WriteString(`<aside class="callout callout-`)
			b.WriteString(html.EscapeString(sanitizeClass(kind)))
			b.WriteString(`"><p class="callout-title">`)
			b.WriteString(html.EscapeString(title))
			b.WriteString("</p>\n")
			b.WriteString(r.renderBlocks(body))
			b.WriteString("</aside>\n")
			return b.String()
		}
	}

	return "<blockquote>\n" + r.renderBlocks(lines) + "</blockquote>\n"
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(strings.ToLower(s))
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func dropFirstNonBlank(lines []string) []string {
	out := append([]string(nil), lines...)
	for i, line := range out {
		if strings.TrimSpace(line) != "" {
			return out[i+1:]
		}
	}
	return nil
}

func listMarker(line string) (bool, string, bool) {
	trimmed := strings.TrimLeft(line, " ")
	if len(trimmed) >= 2 && (trimmed[0] == '-' || trimmed[0] == '*' || trimmed[0] == '+') && trimmed[1] == ' ' {
		return false, strings.TrimSpace(trimmed[2:]), true
	}
	i := 0
	for i < len(trimmed) && trimmed[i] >= '0' && trimmed[i] <= '9' {
		i++
	}
	if i > 0 && i+1 < len(trimmed) && trimmed[i] == '.' && trimmed[i+1] == ' ' {
		return true, strings.TrimSpace(trimmed[i+2:]), true
	}
	return false, "", false
}

func (r *MarkdownRenderer) renderListItem(content string) string {
	if strings.HasPrefix(content, "[ ] ") || strings.HasPrefix(strings.ToLower(content), "[x] ") {
		checked := strings.HasPrefix(strings.ToLower(content), "[x] ")
		rest := strings.TrimSpace(content[4:])
		box := `<input type="checkbox" disabled>`
		if checked {
			box = `<input type="checkbox" disabled checked>`
		}
		return box + " " + r.renderInline(rest)
	}
	return r.renderInline(content)
}

func isTableStart(lines []string, i int) bool {
	if i+1 >= len(lines) {
		return false
	}
	if !strings.Contains(lines[i], "|") {
		return false
	}
	return isTableSeparator(lines[i+1])
}

func isTableSeparator(line string) bool {
	cells := splitTableRow(line)
	if len(cells) == 0 {
		return false
	}
	for _, cell := range cells {
		cell = strings.TrimSpace(cell)
		if len(cell) < 3 {
			return false
		}
		cell = strings.Trim(cell, ":")
		if len(cell) < 3 {
			return false
		}
		for _, r := range cell {
			if r != '-' {
				return false
			}
		}
	}
	return true
}

func splitTableRow(line string) []string {
	line = strings.TrimSpace(line)
	line = strings.TrimPrefix(line, "|")
	line = strings.TrimSuffix(line, "|")
	parts := strings.Split(line, "|")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}

func (r *MarkdownRenderer) renderTable(lines []string) string {
	header := splitTableRow(lines[0])
	var b strings.Builder
	b.WriteString("<table>\n<thead><tr>")
	for _, cell := range header {
		b.WriteString("<th>")
		b.WriteString(r.renderInline(cell))
		b.WriteString("</th>")
	}
	b.WriteString("</tr></thead>\n<tbody>\n")
	for _, line := range lines[2:] {
		cells := splitTableRow(line)
		if len(cells) == 0 {
			continue
		}
		b.WriteString("<tr>")
		for _, cell := range cells {
			b.WriteString("<td>")
			b.WriteString(r.renderInline(cell))
			b.WriteString("</td>")
		}
		b.WriteString("</tr>\n")
	}
	b.WriteString("</tbody>\n</table>\n")
	return b.String()
}

func (r *MarkdownRenderer) uniqueHeadingID(base string) string {
	if base == "" {
		base = "section"
	}
	count := r.headingIDs[base]
	r.headingIDs[base] = count + 1
	if count == 0 {
		return base
	}
	return base + "-" + strconv.Itoa(count+1)
}

func (r *MarkdownRenderer) renderInline(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); {
		switch {
		case strings.HasPrefix(s[i:], "`"):
			if end := strings.Index(s[i+1:], "`"); end >= 0 {
				code := s[i+1 : i+1+end]
				b.WriteString("<code>")
				b.WriteString(html.EscapeString(code))
				b.WriteString("</code>")
				i += end + 2
				continue
			}
		case strings.HasPrefix(s[i:], "![["):
			if end := strings.Index(s[i+3:], "]]"); end >= 0 {
				raw := s[i+3 : i+3+end]
				b.WriteString(r.renderWiki(raw, true))
				i += end + 5
				continue
			}
		case strings.HasPrefix(s[i:], "[["):
			if end := strings.Index(s[i+2:], "]]"); end >= 0 {
				raw := s[i+2 : i+2+end]
				b.WriteString(r.renderWiki(raw, false))
				i += end + 4
				continue
			}
		case strings.HasPrefix(s[i:], "!["):
			if alt, dest, consumed, ok := parseMarkdownLink(s[i+1:]); ok {
				src := r.resolveMarkdownAsset(dest)
				b.WriteString(`<img src="`)
				b.WriteString(html.EscapeString(src))
				b.WriteString(`" alt="`)
				b.WriteString(html.EscapeString(stripInlineMarkdown(alt)))
				b.WriteString(`">`)
				i += consumed + 1
				continue
			}
		case strings.HasPrefix(s[i:], "["):
			if label, dest, consumed, ok := parseMarkdownLink(s[i:]); ok {
				href := r.resolveMarkdownHref(dest)
				b.WriteString(`<a href="`)
				b.WriteString(html.EscapeString(href))
				b.WriteString(`">`)
				b.WriteString(r.renderInline(label))
				b.WriteString(`</a>`)
				i += consumed
				continue
			}
		case strings.HasPrefix(s[i:], "https://") || strings.HasPrefix(s[i:], "http://"):
			href, consumed := consumeBareURL(s[i:])
			b.WriteString(`<a href="`)
			b.WriteString(html.EscapeString(sanitizeHref(href)))
			b.WriteString(`">`)
			b.WriteString(html.EscapeString(href))
			b.WriteString(`</a>`)
			i += consumed
			continue
		case strings.HasPrefix(s[i:], "**"):
			if end := strings.Index(s[i+2:], "**"); end >= 0 {
				b.WriteString("<strong>")
				b.WriteString(r.renderInline(s[i+2 : i+2+end]))
				b.WriteString("</strong>")
				i += end + 4
				continue
			}
		case strings.HasPrefix(s[i:], "__"):
			if end := strings.Index(s[i+2:], "__"); end >= 0 {
				b.WriteString("<strong>")
				b.WriteString(r.renderInline(s[i+2 : i+2+end]))
				b.WriteString("</strong>")
				i += end + 4
				continue
			}
		case strings.HasPrefix(s[i:], "*"):
			if end := strings.Index(s[i+1:], "*"); end >= 0 {
				b.WriteString("<em>")
				b.WriteString(r.renderInline(s[i+1 : i+1+end]))
				b.WriteString("</em>")
				i += end + 2
				continue
			}
		}

		rn, size := utf8.DecodeRuneInString(s[i:])
		if rn == utf8.RuneError && size == 0 {
			break
		}
		b.WriteString(html.EscapeString(string(rn)))
		i += size
	}
	return b.String()
}

func consumeBareURL(s string) (string, int) {
	end := 0
	for end < len(s) {
		r, size := utf8.DecodeRuneInString(s[end:])
		if unicode.IsSpace(r) || r == '<' || r == '"' {
			break
		}
		end += size
	}
	for end > 0 && strings.ContainsRune(".,;:", rune(s[end-1])) {
		end--
	}
	return s[:end], end
}

func parseMarkdownLink(s string) (string, string, int, bool) {
	if !strings.HasPrefix(s, "[") {
		return "", "", 0, false
	}
	closeLabel := strings.Index(s, "](")
	if closeLabel < 0 {
		return "", "", 0, false
	}
	closeDest := strings.Index(s[closeLabel+2:], ")")
	if closeDest < 0 {
		return "", "", 0, false
	}
	label := s[1:closeLabel]
	dest := s[closeLabel+2 : closeLabel+2+closeDest]
	return label, dest, closeLabel + 2 + closeDest + 1, true
}

func (r *MarkdownRenderer) renderWiki(raw string, embed bool) string {
	target, alias := splitAlias(raw)
	target, heading := splitHeading(target)
	display := alias
	if display == "" {
		display = heading
	}
	if display == "" {
		display = path.Base(strings.TrimSuffix(target, ".md"))
	}
	if display == "" {
		display = raw
	}

	if embed || looksLikeAsset(target) {
		if asset, ok := r.resolveAsset(target); ok {
			href := relativeURL(r.current, escapeURLPath(path.Join(r.vault.Config.Source, asset)))
			if isImage(asset) && embed {
				return `<img src="` + html.EscapeString(href) + `" alt="` + html.EscapeString(display) + `">`
			}
			return `<a href="` + html.EscapeString(href) + `">` + html.EscapeString(display) + `</a>`
		}
		if embed {
			if page := r.resolveNote(target); page != nil {
				r.outgoing[page.PageRel] = true
				return `<a class="embed-note" href="` + html.EscapeString(relativeURL(r.current, page.URL)) + `">` + html.EscapeString(display) + `</a>`
			}
		}
	}

	if page := r.resolveNote(target); page != nil {
		r.outgoing[page.PageRel] = true
		href := relativeURL(r.current, page.URL)
		if heading != "" {
			href += "#" + url.PathEscape(slugify(heading))
		}
		return `<a class="wiki-link" href="` + html.EscapeString(href) + `">` + html.EscapeString(display) + `</a>`
	}

	r.warn("unresolved wikilink [[" + raw + "]]")
	return `<span class="broken-link">[[` + html.EscapeString(raw) + `]]</span>`
}

func splitAlias(s string) (string, string) {
	target, alias, ok := strings.Cut(s, "|")
	if !ok {
		return strings.TrimSpace(s), ""
	}
	return strings.TrimSpace(target), strings.TrimSpace(alias)
}

func splitHeading(s string) (string, string) {
	target, heading, ok := strings.Cut(s, "#")
	if !ok {
		return strings.TrimSpace(s), ""
	}
	return strings.TrimSpace(target), strings.TrimSpace(heading)
}

func looksLikeAsset(target string) bool {
	ext := strings.ToLower(path.Ext(target))
	if strings.ContainsAny(ext, " \t") {
		return false
	}
	return ext != "" && ext != ".md"
}

func isImage(rel string) bool {
	switch strings.ToLower(path.Ext(rel)) {
	case ".avif", ".gif", ".jpeg", ".jpg", ".png", ".svg", ".webp":
		return true
	default:
		return false
	}
}

func (r *MarkdownRenderer) resolveNote(target string) *Page {
	target = strings.TrimSpace(strings.TrimSuffix(target, ".md"))
	if target == "" {
		return r.current
	}

	candidates := []string{}
	if path.Dir(r.current.PageRel) != "." {
		candidates = append(candidates, path.Join(path.Dir(r.current.PageRel), target))
	}
	candidates = append(candidates, target)
	for _, candidate := range candidates {
		if page := r.vault.ByPath[strings.ToLower(path.Clean(candidate))]; page != nil {
			return page
		}
	}

	if strings.Contains(target, "/") {
		return nil
	}

	matches := r.vault.ByBase[strings.ToLower(target)]
	if len(matches) == 0 {
		return nil
	}
	if len(matches) == 1 {
		return matches[0]
	}

	best := nearestPage(r.current, matches)
	if best == nil {
		r.warn("ambiguous wikilink [[" + target + "]]")
	}
	return best
}

func nearestPage(current *Page, matches []*Page) *Page {
	bestDistance := 1 << 30
	var best *Page
	tie := false
	for _, candidate := range matches {
		distance := folderDistance(path.Dir(current.PageRel), path.Dir(candidate.PageRel))
		if distance < bestDistance {
			bestDistance = distance
			best = candidate
			tie = false
		} else if distance == bestDistance {
			tie = true
		}
	}
	if tie {
		return nil
	}
	return best
}

func folderDistance(a, b string) int {
	if a == "." {
		a = ""
	}
	if b == "." {
		b = ""
	}
	ap := splitPath(a)
	bp := splitPath(b)
	common := 0
	for common < len(ap) && common < len(bp) && strings.EqualFold(ap[common], bp[common]) {
		common++
	}
	return (len(ap) - common) + (len(bp) - common)
}

func splitPath(s string) []string {
	if s == "" || s == "." {
		return nil
	}
	return strings.Split(s, "/")
}

func (r *MarkdownRenderer) resolveAsset(target string) (string, bool) {
	target = strings.TrimSpace(target)
	if target == "" {
		return "", false
	}
	target = strings.TrimPrefix(path.Clean(target), "./")
	var candidates []string
	if path.Dir(r.current.SourceRel) != "." {
		candidates = append(candidates, path.Join(path.Dir(r.current.SourceRel), target))
	}
	candidates = append(candidates, target)
	for _, candidate := range candidates {
		if rel, ok := r.vault.AssetsByPath[strings.ToLower(candidate)]; ok {
			return rel, true
		}
	}
	if strings.Contains(target, "/") {
		return "", false
	}
	matches := r.vault.AssetsByBase[strings.ToLower(path.Base(target))]
	if len(matches) == 1 {
		return matches[0], true
	}
	if len(matches) > 1 {
		currentDir := path.Dir(r.current.SourceRel)
		sort.Slice(matches, func(i, j int) bool {
			return folderDistance(currentDir, path.Dir(matches[i])) < folderDistance(currentDir, path.Dir(matches[j]))
		})
		if folderDistance(currentDir, path.Dir(matches[0])) != folderDistance(currentDir, path.Dir(matches[1])) {
			return matches[0], true
		}
		r.warn("ambiguous asset [[" + target + "]]")
	}
	return "", false
}

func (r *MarkdownRenderer) resolveMarkdownHref(dest string) string {
	dest = strings.TrimSpace(dest)
	if isExternalOrAbsolute(dest) || strings.HasPrefix(dest, "#") {
		return sanitizeHref(dest)
	}

	cleanDest, anchor := splitURLAnchor(dest)
	if strings.EqualFold(path.Ext(cleanDest), ".md") {
		target := strings.TrimSuffix(cleanDest, ".md")
		candidates := []string{}
		if !strings.HasPrefix(target, "/") && path.Dir(r.current.PageRel) != "." {
			candidates = append(candidates, path.Join(path.Dir(r.current.PageRel), target))
		}
		candidates = append(candidates, strings.TrimPrefix(target, "/"))
		for _, candidate := range candidates {
			if page := r.vault.ByPath[strings.ToLower(path.Clean(candidate))]; page != nil {
				href := relativeURL(r.current, page.URL)
				if anchor != "" {
					href += "#" + url.PathEscape(slugify(anchor))
				}
				r.outgoing[page.PageRel] = true
				return href
			}
		}
	}

	return r.resolveMarkdownAsset(dest)
}

func (r *MarkdownRenderer) resolveMarkdownAsset(dest string) string {
	dest = strings.TrimSpace(dest)
	if isExternalOrAbsolute(dest) || strings.HasPrefix(dest, "#") {
		return sanitizeHref(dest)
	}
	cleanDest, anchor := splitURLAnchor(dest)
	if path.Dir(r.current.SourceRel) != "." && !strings.HasPrefix(cleanDest, "/") {
		cleanDest = path.Join(path.Dir(r.current.SourceRel), cleanDest)
	}
	cleanDest = strings.TrimPrefix(path.Clean(cleanDest), "/")
	href := relativeURL(r.current, escapeURLPath(path.Join(r.vault.Config.Source, cleanDest)))
	if anchor != "" {
		href += "#" + url.PathEscape(anchor)
	}
	return href
}

func splitURLAnchor(s string) (string, string) {
	before, after, ok := strings.Cut(s, "#")
	if !ok {
		return s, ""
	}
	return before, after
}

func isExternalOrAbsolute(s string) bool {
	lower := strings.ToLower(s)
	return strings.HasPrefix(lower, "http://") ||
		strings.HasPrefix(lower, "https://") ||
		strings.HasPrefix(lower, "mailto:") ||
		strings.HasPrefix(lower, "tel:") ||
		strings.HasPrefix(s, "/")
}

func sanitizeHref(href string) string {
	lower := strings.ToLower(strings.TrimSpace(href))
	if strings.HasPrefix(lower, "javascript:") || strings.HasPrefix(lower, "data:") {
		return "#"
	}
	return href
}

func (r *MarkdownRenderer) warn(message string) {
	*r.warnings = append(*r.warnings, r.current.SourceRel+": "+message)
}

func stripInlineMarkdown(s string) string {
	wikiRE := regexp.MustCompile(`!?\[\[([^|\]#]+)(?:#[^|\]]*)?(?:\|([^\]]+))?\]\]`)
	s = wikiRE.ReplaceAllStringFunc(s, func(match string) string {
		m := wikiRE.FindStringSubmatch(match)
		if len(m) > 2 && m[2] != "" {
			return m[2]
		}
		return path.Base(m[1])
	})
	linkRE := regexp.MustCompile(`!?\[([^\]]*)\]\([^)]+\)`)
	s = linkRE.ReplaceAllString(s, "$1")
	for _, marker := range []string{"**", "__", "*", "`"} {
		s = strings.ReplaceAll(s, marker, "")
	}
	return strings.TrimSpace(s)
}

func plainText(markdown string) string {
	text := stripInlineMarkdown(markdown)
	lines := strings.Split(text, "\n")
	out := make([]string, 0, len(lines))
	inFence := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}
		if inFence || trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, ">") {
			trimmed = strings.TrimSpace(strings.TrimPrefix(trimmed, ">"))
		}
		out = append(out, strings.Trim(trimmed, "#-* "))
	}
	return strings.Join(strings.Fields(strings.Join(out, " ")), " ")
}

func extractTags(markdown string) []string {
	re := regexp.MustCompile(`(^|\s)#([A-Za-z0-9_/-]+)`)
	matches := re.FindAllStringSubmatch(markdown, -1)
	seen := map[string]bool{}
	var tags []string
	for _, match := range matches {
		tag := match[2]
		if tag == "" || seen[tag] {
			continue
		}
		seen[tag] = true
		tags = append(tags, tag)
	}
	sort.Strings(tags)
	return tags
}

func excerpt(text string, limit int) string {
	text = strings.TrimSpace(strings.Join(strings.Fields(text), " "))
	if len(text) <= limit {
		return text
	}
	return strings.TrimSpace(text[:limit]) + "..."
}

func slugify(s string) string {
	s = strings.ToLower(stripInlineMarkdown(s))
	var b strings.Builder
	lastDash := false
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash {
			b.WriteRune('-')
			lastDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

func escapeURLPath(rel string) string {
	rel = strings.TrimPrefix(path.Clean(strings.ReplaceAll(rel, "\\", "/")), "/")
	if rel == "." || rel == "" {
		return ""
	}
	parts := strings.Split(rel, "/")
	for i, part := range parts {
		parts[i] = url.PathEscape(part)
	}
	return strings.Join(parts, "/")
}

func relativeRoot(from *Page) string {
	if from == nil || from.IsHome || from.URL == "" {
		return ""
	}
	trimmed := strings.Trim(strings.TrimSuffix(from.URL, "/"), "/")
	if trimmed == "" {
		return ""
	}
	levels := len(strings.Split(trimmed, "/"))
	return strings.Repeat("../", levels)
}

func relativeURL(from *Page, target string) string {
	target = strings.TrimPrefix(target, "/")
	root := relativeRoot(from)
	if target == "" {
		if root == "" {
			return "./"
		}
		return root
	}
	return root + target
}

const defaultPageTemplate = `{{.Generated}}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{if .Page.IsHome}}{{.Site.Title}}{{else}}{{.Page.Title}} - {{.Site.Title}}{{end}}</title>
  <link rel="stylesheet" href="{{.CSSURL}}">
  <script>window.ONYX_ROOT = {{.RootScript}};</script>
  {{if .Search}}<script defer src="{{.JSURL}}"></script>{{end}}
</head>
<body>
  <a class="skip-link" href="#content">Skip to content</a>
  <div class="onyx-shell">
    <aside class="onyx-sidebar">
      <a class="onyx-brand" href="{{.HomeURL}}">{{.Site.Title}}</a>
      {{if .Search}}
      <div class="onyx-search">
        <input id="onyx-search" type="search" autocomplete="off" placeholder="Search notes">
        <div id="onyx-search-results" class="onyx-search-results" hidden></div>
      </div>
      {{end}}
      <nav aria-label="Notes">
        {{.Nav}}
      </nav>
    </aside>
    <main id="content" class="onyx-main">
      <article class="onyx-note">
        <header class="onyx-note-header">
          {{if .Page.SourceRel}}<p class="onyx-path">{{.Page.SourceRel}}</p>{{end}}
          <h1>{{.Page.Title}}</h1>
          {{if .ShowSource}}<a class="onyx-source" href="{{.Page.SourceURL}}">Markdown</a>{{end}}
        </header>
        <div class="onyx-content">
          {{.Page.HTML}}
        </div>
        {{if and .Backlinks .Site.Title}}
        <section class="onyx-backlinks" aria-labelledby="backlinks-title">
          <h2 id="backlinks-title">Linked From</h2>
          <ul>
            {{range .Backlinks}}<li><a href="{{.URL}}">{{.Title}}</a> <span>{{.Path}}</span></li>{{end}}
          </ul>
        </section>
        {{end}}
      </article>
    </main>
  </div>
</body>
</html>
`

const defaultCSS = `:root {
  color-scheme: light;
  --bg: #f7f5ef;
  --panel: #efece3;
  --text: #20201d;
  --muted: #6d6a60;
  --line: #ddd7ca;
  --accent: #2f6f73;
  --accent-2: #8a5a35;
  --code: #ece5d8;
  --warn: #9a3412;
  --hover: #fdf6e7;
  --active: #f4ead3;
  --ring: rgb(47 111 115 / 22%);
  --radius: 8px;
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}

* { box-sizing: border-box; }
html { min-height: 100%; }
body {
  min-height: 100%;
  margin: 0;
  background: var(--bg);
  color: var(--text);
  line-height: 1.65;
}

a { color: var(--accent); text-decoration-thickness: .08em; text-underline-offset: .18em; }
a:hover { color: var(--accent-2); }

.skip-link {
  position: absolute;
  top: .75rem;
  left: .75rem;
  transform: translateY(-200%);
  background: var(--text);
  color: var(--bg);
  padding: .45rem .7rem;
  border-radius: 6px;
  z-index: 10;
}
.skip-link:focus { transform: translateY(0); }

.onyx-shell {
  display: grid;
  grid-template-columns: minmax(17rem, 22rem) minmax(0, 1fr);
  min-height: 100vh;
}

.onyx-sidebar {
  position: sticky;
  top: 0;
  height: 100vh;
  overflow: auto;
  border-right: 1px solid var(--line);
  background: var(--panel);
  padding: 1.1rem;
}

.onyx-brand {
  display: block;
  color: var(--text);
  font-size: 1.05rem;
  font-weight: 750;
  line-height: 1.2;
  margin-bottom: 1rem;
  text-decoration: none;
}

.onyx-search { position: relative; margin-bottom: 1rem; }
.onyx-search input {
  width: 100%;
  border: 1px solid var(--line);
  border-radius: 7px;
  background: #fffdfa;
  color: var(--text);
  font: inherit;
  line-height: 1.2;
  padding: .55rem .65rem;
  transition: border-color .12s ease, box-shadow .12s ease;
}
.onyx-search input:focus {
  outline: none;
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--ring);
}
.onyx-search-results {
  position: absolute;
  z-index: 5;
  top: calc(100% + .35rem);
  left: 0;
  right: 0;
  max-height: 60vh;
  overflow: auto;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: #fffdfa;
  box-shadow: 0 14px 28px rgb(32 32 29 / 15%);
}
.onyx-search-results a {
  display: block;
  padding: .65rem .75rem;
  color: var(--text);
  text-decoration: none;
  border-bottom: 1px solid var(--line);
}
.onyx-search-results a:last-child { border-bottom: 0; }
.onyx-search-results strong { display: block; line-height: 1.25; }
.onyx-search-results span {
  display: block;
  color: var(--muted);
  font-size: .82rem;
  line-height: 1.35;
  margin-top: .15rem;
}

.nav-tree, .nav-tree ul {
  list-style: none;
  margin: 0;
  padding-left: 0;
}
.nav-tree ul {
  margin-left: .55rem;
  padding-left: .55rem;
  border-left: 1px solid var(--line);
}
.nav-tree li { margin: .05rem 0; }
.nav-tree a, .nav-tree span, .nav-tree summary {
  display: flex;
  align-items: center;
  gap: .5rem;
  color: var(--muted);
  font-size: .92rem;
  line-height: 1.3;
  padding: .28rem .45rem;
  text-decoration: none;
  border-radius: 7px;
  transition: background .12s ease, color .12s ease;
}
.nav-tree a:hover, .nav-tree summary:hover { background: var(--hover); color: var(--text); }
.nav-tree a[aria-current="page"] {
  background: var(--active);
  color: var(--accent);
  font-weight: 700;
}

/* Folder rows: a caret that rotates open, with a folder-toned label. */
.nav-tree details { margin: .05rem 0; }
.nav-tree summary {
  cursor: pointer;
  list-style: none;
  font-weight: 600;
  color: var(--text);
}
.nav-tree summary::-webkit-details-marker { display: none; }
.nav-tree summary::before {
  content: "";
  flex: 0 0 auto;
  width: 0;
  height: 0;
  border-left: 5px solid currentColor;
  border-top: 4px solid transparent;
  border-bottom: 4px solid transparent;
  opacity: .5;
  transition: transform .15s ease;
}
.nav-tree details[open] > summary::before { transform: rotate(90deg); }
.nav-tree summary a, .nav-tree summary span {
  display: inline;
  gap: 0;
  padding: 0;
  color: inherit;
  font: inherit;
}
.nav-tree summary a:hover { background: none; color: inherit; }

/* File rows: a small square dot, filled when it's the current page. */
.nav-tree li > a::before {
  content: "";
  flex: 0 0 auto;
  width: .4rem;
  height: .4rem;
  margin: 0 .05rem;
  border-radius: 2px;
  background: currentColor;
  opacity: .35;
}
.nav-tree li > a:hover::before { opacity: .6; }
.nav-tree li > a[aria-current="page"]::before { opacity: 1; }

.onyx-main {
  width: min(100%, 78rem);
  padding: clamp(1.2rem, 4vw, 4rem);
}
.onyx-note {
  max-width: 52rem;
}
.onyx-note-header {
  border-bottom: 1px solid var(--line);
  margin-bottom: 1.35rem;
  padding-bottom: 1rem;
}
.onyx-path {
  color: var(--muted);
  font-size: .85rem;
  line-height: 1.2;
  margin: 0 0 .35rem;
}
.onyx-note h1 {
  font-size: clamp(2rem, 5vw, 3.2rem);
  letter-spacing: 0;
  line-height: 1.05;
  margin: 0;
}
.onyx-source {
  display: inline-block;
  font-size: .86rem;
  margin-top: .65rem;
}

.onyx-content h2, .onyx-content h3, .onyx-content h4 {
  line-height: 1.15;
  margin-top: 2rem;
}
.onyx-content p, .onyx-content ul, .onyx-content ol, .onyx-content blockquote, .onyx-content table, .onyx-content pre {
  margin-bottom: 1rem;
}
.onyx-content img {
  max-width: 100%;
  height: auto;
  border-radius: 8px;
}
.onyx-content code {
  background: var(--code);
  border-radius: 5px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: .92em;
  padding: .08rem .25rem;
}
.onyx-content pre {
  background: #24231f;
  color: #f7f5ef;
  overflow: auto;
  padding: 1rem;
  border-radius: 8px;
}
.onyx-content pre code {
  background: transparent;
  color: inherit;
  padding: 0;
}
.onyx-content blockquote {
  border-left: 3px solid var(--line);
  color: var(--muted);
  margin-left: 0;
  padding-left: 1rem;
}
.onyx-content table {
  border-collapse: collapse;
  display: block;
  max-width: 100%;
  overflow-x: auto;
}
.onyx-content th, .onyx-content td {
  border: 1px solid var(--line);
  padding: .45rem .6rem;
  vertical-align: top;
}
.onyx-content th { background: var(--panel); text-align: left; }

.callout {
  border: 1px solid var(--line);
  border-left: 4px solid var(--accent);
  border-radius: 8px;
  margin: 1rem 0;
  padding: .8rem 1rem;
  background: #fffdfa;
}
.callout-title {
  color: var(--accent);
  font-weight: 800;
  margin: 0 0 .35rem;
}
.callout-warning, .callout-danger, .callout-caution { border-left-color: var(--warn); }
.callout-warning .callout-title, .callout-danger .callout-title, .callout-caution .callout-title { color: var(--warn); }

.broken-link {
  color: var(--warn);
  font-weight: 700;
}
.embed-note {
  border: 1px solid var(--line);
  border-radius: 6px;
  display: inline-block;
  padding: .05rem .35rem;
  text-decoration: none;
}

.onyx-backlinks {
  border-top: 1px solid var(--line);
  margin-top: 2rem;
  padding-top: 1rem;
}
.onyx-backlinks h2 {
  font-size: 1rem;
  letter-spacing: 0;
  margin: 0 0 .5rem;
}
.onyx-backlinks ul { padding-left: 1.1rem; }
.onyx-backlinks span {
  color: var(--muted);
  font-size: .85rem;
}

@media (max-width: 820px) {
  .onyx-shell { display: block; }
  .onyx-sidebar {
    position: static;
    height: auto;
    max-height: 45vh;
    border-right: 0;
    border-bottom: 1px solid var(--line);
  }
  .onyx-main { padding: 1.2rem; }
  .onyx-note h1 { font-size: 2rem; }
}
`

const defaultJS = `(function () {
  const input = document.getElementById("onyx-search");
  const results = document.getElementById("onyx-search-results");
  if (!input || !results) return;

  const root = window.ONYX_ROOT || "";
  let index = [];

  fetch(root + "public/search-index.json")
    .then((response) => response.ok ? response.json() : [])
    .then((items) => { index = Array.isArray(items) ? items : []; })
    .catch(() => { index = []; });

  function escapeHTML(value) {
    return String(value).replace(/[&<>"']/g, (ch) => ({
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;"
    })[ch]);
  }

  function score(item, terms) {
    const haystack = [
      item.title || "",
      item.path || "",
      item.excerpt || "",
      (item.headings || []).join(" "),
      (item.tags || []).join(" ")
    ].join(" ").toLowerCase();
    let total = 0;
    for (const term of terms) {
      if (!haystack.includes(term)) return 0;
      total += (item.title || "").toLowerCase().includes(term) ? 4 : 1;
      total += (item.path || "").toLowerCase().includes(term) ? 2 : 0;
    }
    return total;
  }

  function withRoot(url) {
    return root + (url || "./");
  }

  function render() {
    const terms = input.value.trim().toLowerCase().split(/\s+/).filter(Boolean);
    if (!terms.length) {
      results.hidden = true;
      results.innerHTML = "";
      return;
    }
    const matches = index
      .map((item) => ({ item, value: score(item, terms) }))
      .filter((entry) => entry.value > 0)
      .sort((a, b) => b.value - a.value || String(a.item.title).localeCompare(String(b.item.title)))
      .slice(0, 12);

    results.innerHTML = matches.length
      ? matches.map(({ item }) => '<a href="' + escapeHTML(withRoot(item.url)) + '"><strong>' + escapeHTML(item.title) + '</strong><span>' + escapeHTML(item.excerpt || item.path || "") + '</span></a>').join("")
      : '<a href="#"><strong>No matches</strong><span>Try a different phrase.</span></a>';
    results.hidden = false;
  }

  input.addEventListener("input", render);
  input.addEventListener("focus", render);
  document.addEventListener("click", (event) => {
    if (!results.contains(event.target) && event.target !== input) results.hidden = true;
  });
  document.addEventListener("keydown", (event) => {
    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") {
      event.preventDefault();
      input.focus();
      input.select();
    }
    if (event.key === "Escape") {
      results.hidden = true;
      input.blur();
    }
  });
})();`
